### ISSUE TITLE
New category suggestion: iOS Development Change Trackers 

### ISSUE THREAD

**Issue by byaruhaf** [daveverwer/iOSDevDirectory#234]
Would like to add a section for sites that track changes SDK, Swift versions and app store review guidelines. These are not exactly blog or newsletters so not sure which section to add them, thus recommending they get there own section. Need a better name than "Change Trackers".
Example site's for this category are:

[Apple Platform SDK API Differences](http://codeworkshop.net/objc-diff/sdkdiffs/)
[What's new in Swift?](https://www.whatsnewinswift.com/)
[App store review guidelines history](http://www.appstorereviewguidelineshistory.com/)

**Comment by daveverwer** [comment]
Apologies for not getting to this until now, I've had a busy week and I wanted to think about how best to handle this. Thank you for taking the time to submit it.

1. First up, Paul's "What's new in Swift" is a great fit, but it unfortunately does not have an RSS feed. The main idea of the site was that people would subscribe to the blogs listed here, and actually RSS feed is a required field right now. The issue with Paul's site is that the way it works (which is great) doesn't really fit with the concept of RSS very well. I could remove the requirement for an RSS feed just to get it listed here, but I fear that may start other people submitting without feeds too, which would be a shame. Maybe @twostraws has an opinion?

2. I think Matt's "Apple Platform SDK API Differences" would be a great fit for the site. I'm reluctant to put just a couple of blogs into a category though so maybe this is a chance to update the "Official Apple Blogs" section to be something like "Platform and SDK Updates"?

3. Finally, I think "App store review guidelines history" would make a great link in that section too, but I don't think it's being updated anymore. I think there have been quite a few changes to the review guidelines that have happened since the site last updated in June 2018. I still think it could be added though.

If you'd like to put together a PR for points 2 and 3 and the category rename change, that'd be great! Thank you.

Dave
