### ISSUE TITLE
RSS feeds of categories

### ISSUE THREAD

**Issue by ObscureBug** [daveverwer/iOSDevDirectory#660]
After seeing a site that aggregates data from this site / project,  I was trying to figure out how to ingest the data into NetNewsWire to watch for updates when new sites are added.

The per category OPML files are great,  but they're ephemeral and only represent the tip of the tree.  I'm trying figure out if there is an easy way to produce RSS feeds of the different categories so my RSS reader can watch for new additions to the database.  The git history provides the ordering that RSS feed need.

The entire goal is to have an automated way to be able to monitor for changes in the individual categories so I can investigate a new blog, then decide whether to subscribe to that new blog.  Unfortunately,  I know very little any of the technologies to make this possible.

**Comment by daveverwer** [comment]
Hi Greg, and thanks for the note!

Unfortunately, what you’re asking for us outside the scope of this site. As you noted, several sites have already produced feed aggregators powered by the directory. For example, https://iosdevblogs.com/.

I deliberately didn’t want to write an aggregator, and still don’t want to. I’ve done it before and it was a pain to maintain.

However! I do have a solution for you, and it’s the same solution I use, and have been using since I started the directory. There’s a service named [Inoreader](https://www.inoreader.com) that lets you subscribe to an OPML file. It tracks any additions/deletions and lets you consume an RSS feed with the resulting aggregation, which you can add to NNW or any other feed reader.

I’ll close this issue now, and I hope you get on well with Inoreader!

Dave

**Comment by ObscureBug** [comment]
Hi Dave,

Thanks for the response.  Makes sense.  I'll give inoreader a try.

Cheers,
Greg
